{% set name = "rhumba" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mamba-org/rhumba/archive/{{ version }}.tar.gz
  sha256: 1df0833271d0bd23832aa30a920038c65d809837c8fb6931ac258fa5d18b32e8

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - libmamba >=0.25.0,<0.26
    - cpp-filesystem
    - nlohmann_json
    - r-base
    - r-rcpp
  run:
    - r-base
    - r-rcpp
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('rhumba')"           # [not win]
    - "\"%R%\" -e \"library('rhumba')\""  # [win]

about:
  home: https://github.com/mamba-org/rhumba
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'R bindings for Mamba.'

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
    - marimeireles
    - adriendelsalle
