{% set name = "rhumba" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mamba-org/rhumba/archive/{{ version }}.tar.gz
  sha256: 4c863e762b0936673694fab99a805ec7b1fcd5954721d659de807e41193ff16e

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('cxx') }}            # [not win]
    - make
  host:
    - libmamba
    - cpp-filesystem
    - nlohmann_json
    - r-base
    - r-rcpp
  run:
    - r-base
    - r-rcpp

test:
  commands:
    - $R -e "library('rhumba')"           # [not win]
    - "\"%R%\" -e \"library('rhumba')\""  # [win]

about:
  home: https://github.com/marimeireles/rhumba
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: R bindings for Mamba.

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
    - marimeireles
